image: java:8-jdk

stages:
  - build
  - deploy

before_script:

cache:
  key: "$CI_BUILD_NAME"

build:
  stage: build
  script:
    - ./mvnw clean package -e -U
    - cat target/site/jacoco/index.html

deploy:
  stage: deploy
  script:
    - ./mvnw clean package -e -U
    - echo "Deploying to Live server"
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - echo "Copying jar to server"
    - scp target/skillwill.jar ubuntu@52.57.133.142:/srv/http/skillwill.jar
    - ssh ubuntu@52.57.133.142 sudo systemctl restart skillwill.service
  only:
    - master
  when: manual
