image: openjdk:10-slim

stages:
  - build
  - deploy-smaland
  - deploy-live

before_script:

cache:
  key: "$CI_BUILD_NAME"

build:
  stage: build
  script:
    - ./mvnw clean package -e -U
  artifacts:
    paths:
      - target/skillwill.jar
    expire_in: 1 week

deploy-smaland:
  stage: deploy-smaland
  environment:
    name: Smaland
    url: http://smaland.skillwill.sinnerschrader.com
  dependencies:
      - build
  script:
    - echo 'Setting up SSH client'
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - echo 'Copying jar to server'
    - scp target/skillwill.jar ubuntu@35.157.217.249:/srv/http/skillwill.jar
    - echo 'Restarting smaland application'
    - ssh ubuntu@35.157.217.249 sudo systemctl restart skillwill.service
  when: manual

deploy-live:
  stage: deploy-live
  environment:
    name: Live
    url: https://skillwill.sinnerschrader.com
  dependencies:
      - build
  script:
    - echo 'Setting up SSH client'
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval $(ssh-agent -s)
    - ssh-add <(echo "$SSH_PRIVATE_KEY")
    - mkdir -p ~/.ssh
    - '[[ -f /.dockerenv ]] && echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config'
    - echo 'Copying jar to server'
    - scp target/skillwill.jar ubuntu@52.57.133.142:/srv/http/skillwill.jar
    - echo 'Restarting live application'
    - ssh ubuntu@52.57.133.142 sudo systemctl restart skillwill.service
  only:
    - master
  when: manual
